# Generated by Django 4.1.7 on 2023-02-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50, verbose_name='Вид животного')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
                ('full_text', models.TextField(verbose_name='Описание')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
                ('img', models.ImageField(upload_to='%Y/%m/%d', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Зверь',
                'verbose_name_plural': 'Зверушки',
            },
        ),
    ]
